user_admin:
  path:   /user
  defaults:
    _controller: AdminBundle:Admin:user
useredit_admin:
  path:   /user/{id}
  defaults:
    _controller: AdminBundle:Admin:user
userdelete_admin:
  path:   /user/del/{id}
  defaults:
    _controller: AdminBundle:Admin:userdelete

category_admin:
  path:   /category
  defaults:
    _controller: AdminBundle:Admin:category
categoryedit_admin:
  path:   /category/{id}
  defaults:
    _controller: AdminBundle:Admin:category
categorydelete_admin:
  path:   /category/del/{id}
  defaults:
    _controller: AdminBundle:Admin:categorydelete



product_admin:
  path:   /product
  defaults:
    _controller: AdminBundle:Admin:product
productedit_admin:
  path:   /product/{id}
  defaults:
    _controller: AdminBundle:Admin:product
productdelete_admin:
  path:   /product/del/{id}
  defaults:
    _controller: AdminBundle:Admin:productdelete
index_admin:
  path:   /
  defaults:
    _controller: AdminBundle:Admin:index
order_admin:
  path:   /order
  defaults:
    _controller: AdminBundle:Admin:order
ordershow_admin:
  path:   /order/{id}
  defaults:
    _controller: AdminBundle:Admin:ordershow
orderdelete_admin:
  path:   /order/del/{id}
  defaults:
    _controller: AdminBundle:Admin:orderdelete
