<?php

namespace ECommBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
* BigBrowserRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class BigBrowserRepository extends EntityRepository
{
}
