<?php

namespace ECommBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
* OrderRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class OrderRepository extends EntityRepository
{
  public function count()
  {
      $qb = $this->createQueryBuilder('o');
      $qb ->select($qb->expr()->count('o'));
      return (int) $qb->getQuery()->getSingleScalarResult();
  }
}
