<?php

namespace ECommBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{

  /**
   *
   */
  public function existProduit ($idProduit) {

   $qb =  $this->createQueryBuilder('p')
     ->andWhere('p.id = :id')
       ->setParameter('id', $idProduit)
   ;

   return sizeof($qb->getQuery()->getResult()) == 1;
 }

 public function getProduits()
  {
    $query = $this->createQueryBuilder('a')
      // Jointure sur l'attribut image
      ->leftJoin('a.medias', 'm')
      ->addSelect('m')
    ;

    return $query
    ->getQuery()
    ->getResult();
  }

}
