<?php

namespace ECommBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{

  /**
   *
   */
  public function existProduit ($nomProduit) {

   $qb =  $this->createQueryBuilder('p')
     ->andWhere('p.nom = :nom')
       ->setParameter('nom', $nomProduit)
   ;

   return sizeof($qb->getQuery()->getResult()) == 1;
 }
}
